import './globals.css';
// import { Bebas_Neue, Rubik, Poppins } from 'next/font/google';

// const bebas = Bebas_Neue({
//   subsets: ['latin'],
//   weight: ['400'],
//   display: 'swap',
//   variable: '--font-bebas',
// })
// const rubik = Rubik({
//   subsets: ['latin'],
//   weight: ['300', '500', '700'],
//   display: 'swap',
//   variable: '--font-rubik',
// })
// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['200', '400', '800'],
//   display: 'swap',
//   variable: '--font-poppins',
// })


export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
