import './globals.css';
import Navbar from './pages/dashboard/navbar/Navbar';
// import "tw-elements-react/dist/css/tw-elements-react.min.css";
// import { Roboto } from "next/font/google";

// const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className='font-roboto'>
    { children }
    </div>
  )
}
